### PR TITLE
Database Name - changed recommended value

### PR DESCRIPTION
**Pull request by alpinus4**
When I filled "Database Name:" field with a value that is advised in the commentary: "(This is the name of the LibreHealth EHR database in MySQL - 'LibreHealth EHR' is the recommended)", I had an error. 
I've changed recommended value to "libreehr", which works.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Not valid. No. This is for documentation.

**Comment by teryhill** [comment]
@alpinus4  grab a task for fixing a bug and submit this under it

**Comment by aethelwulffe** [comment]
This IS DOCUMENTATION.
It is _context documentation_ of the absolute most important sort.  It is also a bug.  It is also very darn good catch @alpinus4 
Excellent job, and thank you.

**Comment by alpinus4** [comment]
@teryhill Ok, when someone review my current task, I'll do it :)
@aethelwulffe :)

**Comment by Trodrige** [comment]
Small change, Great importance!!!

**Comment by robbyoconnor** [comment]
No spaces in the DB name.

**Comment by robbyoconnor** [comment]
This is fine -- I may have misread this...sorry folks

**Pull request merged**
