### PR TITLE
added ids to widget rows, removed auto-loading of past encounters tab

### PR DESCRIPTION
**Pull request by kchapple**

### CODE REVIEW

**Comment by teryhill** [comment]
I am assuming that this is for some of that magical stuff that does nothing for us now

**Comment by tmccormi** [comment]
Yes, but it's good practice to include ID in HTML for CSS and the hooks give us power to do plugins ...
more plugins in more places!  That's my motto

**Comment by tmccormi** [comment]
Removing the autoloading encounters history tab could be debatable.  I don't like it myself and you can open it with a click on the title bar view history.

What do y'all  think?

**Comment by teryhill** [comment]
It ain't in demographics or options so we must not use it

**Comment by tmccormi** [comment]
Not sure if that was sarcasm or not .... :-)

**Comment by teryhill** [comment]
no not sarcasm, I don't  interact regularly with the code it is in so I don't think it is applicable to me yet

**Comment by aethelwulffe** [comment]
Mongo dunno.
I say give it a try.  If it is configurable as a default tab/widget, then there you go.

**Comment by teryhill** [comment]
Is there a standard format y'all want for them, "Yes, but it's good practice to include ID in HTML for CSS and the hooks give us power to do plugins "

**Comment by aethelwulffe** [comment]
$widgetId = str_replace( " ", "_", $label ) . "_widget";

So, looks like right now, whatever the $label is, it removes spaces and 
adds _widget.

I suppose that is some sort of standard...so I guess you have to make 
sure not to use the same label for two things, hunh?  No sanity check there.

**Comment by tmccormi** [comment]
Different topic, but yes, ID should be unique and CLASS for common  CSS.

**Pull request merged**
