### PR TITLE
Theme and asset consolidation

### PR DESCRIPTION
**Pull request by aethelwulffe**
Moving assets used for styling of the application to interface/themes.

### CODE REVIEW

**Comment by tmccormi** [comment]
This looks fine.  @aethelwulffe Have you tested or do you need me to?

**Comment by aethelwulffe** [comment]
I tested while developing, but there are many twists between here and there.  I like to see the stuff run on linux as well.  Otherwise I have to set my machine to case-sensitive directories and some other stuff.
  If you are set up to pull down and run easily, please do test.

**Comment by tmccormi** [comment]
That's what  figured, will do.

**Comment by aethelwulffe** [comment]
bump

**Comment by aethelwulffe** [comment]
Tested each and every theme on Ubuntu16.04 and Win10 Enterprise.  All works.

**Comment by aethelwulffe** [comment]
This was desktop 16.04 with permissions pretty loose, but I don't think that will affect anything.  Primary linux concern was the default case-sensitive issue.

**Pull request merged**
