### PR TITLE
added external javascript file to check type validation

### PR DESCRIPTION
**Pull request by nileshprasad137**
This PR is a replacement of #497 for better type validation and usability.

Summary of changes::
1. Currently added an external javascript file to check type validation for Email ,Urls and Phone Numbers(US).
2. For test purpose , modified `interface/usergroup/addrbook_edit.php` . 
3. URL's can have following types: http://www.google.com.. or www.google.com or google.com.

Other Type validations would be added soon.

### CODE REVIEW

**Comment by nileshprasad137** [comment]
I'll need some guidance to validate telephone fields , as I am not sure which format is expected there.
Also , I'll be very busy for next few days , as I have my Mid-Semester Exams till Thursday. :sweat:

**Comment by aethelwulffe** [comment]
tel is supported by all browsers...

**Comment by nileshprasad137** [comment]
@tmccormi Why a `question` label?  :stuck_out_tongue:  I'll work on `tel` type and make changes soon. I am having my mid-sem , so currently a bit busy , but I'll make changes very soon.

**Comment by tmccormi** [comment]
Your asked a question that has not been answered yet int the form of "I'll need so guidance.."  this is not a pull request that is ready to merge yet, just trying to keep the confusion down to a minimum level.  Get your mid-terms locked.  No worries.

**Comment by aethelwulffe** [comment]
School, school, school everyone...but yes, question on a pull request is a bit odd.  I will add WIP :)

**Comment by nileshprasad137** [comment]
@aethelwulffe @tmccormi @teryhill 

Last commit fixes phone-validation in forms to some extent. Whenever the user enters a wrong phone-number , text-field would be bordered with red as well as save button would be disabled. Also, if user has entered valid phone-number, The number would be reformatted. 
All this has been done using JS, but I have not yet touched globals.php.  
A lot more can be done more.  
phone

**Comment by aethelwulffe** [comment]
Pulled and tested as per the address book example above.  Implementation could go on, but this is a good start:  NEEDS API documentation in a validation section.

**Comment by nileshprasad137** [comment]
@aethelwulffe Yes. This can be extended . Note that ,we have type="submit" and at some forms and  <a href=".."> at some forms for the submit option. We would need to make it uniform throughout.

**Pull request merged**
