### PR TITLE
Tweaking #539 html2pdf upgrade

### PR DESCRIPTION
**Pull request by aethelwulffe**
This removes the composer files and all that, which may not be wise.  I have not verified if there are any issues associated with fonts removed either.  I suspect you may want to just cherry pick out of this, or use it as a reference.
Moved the directory back to just html2pdf
*included updated files
*removed currently unused files
*checked all references in the original html2pdf mod branch to ensure
everything was cool with the new versions
*updated documentation.
NOTE: if anyone feels that additional fonts are required at this time,
yell now.

### CODE REVIEW

**Comment by aethelwulffe** [comment]
@pri2si17-1997 You probably want to keep the composer files and the like that I snuffed in this branch.  This is just my input.

**Comment by pri2si17-1997** [comment]
@aethelwulffe I think they are not required.

**Comment by aethelwulffe** [comment]
Well, I know squat about composer.  I am a "drag and drop" integrator myself.   I figured you might have some different opinions though.

**Comment by tmccormi** [comment]
@aethelwulffe  "tweaking" seems like a weak description for something that effected 279 files.   what do you mean by "might want to cherry-pick this"?

**Comment by aethelwulffe** [comment]
We are discussing this in chat...sorry.
Basically he brought in the full package with updated content, added it as a new directory etc...
This is a branch off of his PR that sort of does the same thing with his newer code that was done with the original move of these files.  Namely, adding docs, removing excess files etc...  279 files indicates that he added 210 files that had been deleted previously, and the remaining 68 were moved back over to the original directory name of /html2pdf.
The "cherry pick" reference was not necessarily a GIT term, but a "use this as a reference for what I am talking about".  To that end, the question was if he should include the composer files and any additional fonts that I dropped in this branch.

**Pull request merged**
