### PR TITLE
Made SSL Certificate Tab responsive

### LINKED ISSUE #806: Make content in SSL Certificate tab responsive
Go to Admin->Other->Certificate. Open three different tabs. Notice that the content is not responsive.

### PR DESCRIPTION
**Pull request by Jdew192837**
Moved the form into the div and changed the width

Fixes #806

Before:
====
screenshot 57

After:
====
screenshot 56

### CODE REVIEW

**Comment by Trodrige** [comment]
@Jdew192837 try opening 4 tabs.

**Comment by Trodrige** [comment]
The example inputs are still out of the div. It doesn't look good to me. Try something here.
I think the examples should be 'placehoders' instead. What do you think?

**Comment by Jdew192837** [comment]
@Trodrige I think that, if you have the examples as a button, and on press the example will show.
Ex.
"Example (button)" "hostname@domain.com" 
Or have them as a comment whereby if you hover over the text, it will appear not on the page but as a comment.

**Comment by Trodrige** [comment]
I stand with placeholders, simple and straight to the point. User's don't have to hover or click before seeing the type of input required.

**Comment by Jdew192837** [comment]
Updated:
=======

## Before
sslbeforeforreal

## After
sslbefore

**Comment by Trodrige** [comment]
The 'Client certificate validation period' is in days. I think the placeholder should be "How many days?" or "Number of days" or something similar to these

**Comment by Jdew192837** [comment]
I think it's better if we describe that in the name and a number as placeholder to make it clear for users.

Currently, I'm doing Client certificate validation period (in days), and placeholder is 365. What do you think?

@Trodrige

**Comment by Trodrige** [comment]
Go ahead boy. Let's see what we get when you're done. Good job.

**Comment by Trodrige** [comment]
More eyes here @teryhill @tmccormi @aethelwulffe

**Comment by aethelwulffe** [comment]
OK, Full eyes merge here.

**Comment by aethelwulffe** [comment]
Gonzer!

**Pull request merged**
