### PR TITLE
Changed the interval and added a no refresh on the calendar

### PR DESCRIPTION
**Pull request by teryhill**
Made the changes as a result of the check for new appointments being
fired to often

### CODE REVIEW

**Comment by teryhill** [comment]
@azwreith check out the discussion on the forums https://forums.librehealth.io/t/problems-on-ehr-demo-sites/1186

**Comment by aethelwulffe** [comment]
Awaiting other requested reviews...

**Comment by azwreith** [comment]
Sorry for being gone so long, it's my last semester of college and I have a lot of stuff to get done.

Ohh I see, that constant polling might indeed be an issue. In that case setting the auto refetch rate longer and refetching the events every time a new event is added is a better idea.

**Comment by aethelwulffe** [comment]
I honestly feel that every 3-5 seconds as a floor() is waaaay enough.  This is a web script, thingie, not an FPS.

**Comment by tmccormi** [comment]
No frontdesk runs so fast that 60 secs is too long for the refresh.  A manual refresh if desired is also always possible.

**Pull request merged**
