### PR TITLE
Changed to reflect table

### PR DESCRIPTION
**Pull request by teryhill**
Field in table 25 char only using 10 in program. User needed to send note on drug due to new 2017 hcpcs requirement. This field could stand to be expanded in the table to a larger value

### CODE REVIEW

**Comment by teryhill** [comment]
@tmccormi @aethelwulffe I think the field size in the billing table needs to be changed to 50 or 75 char instead of the current value of 25 char.

**Comment by teryhill** [comment]
how do I need to change the field size then. We don't have an upgrade script any more, do we?

**Comment by tmccormi** [comment]
Just edit database.sql - only supporting new installs officially.    Upgrade and migrations scripts with the 1.01 release.

**Comment by teryhill** [comment]
So what do we want 50 or 75 or more @tmccormi @aethelwulffe

**Comment by tmccormi** [comment]
I'm not sure what it's purpose is even.  So I abstain from voting.

**Comment by teryhill** [comment]
This is the explanation from the clearing house

noc_explain

**Comment by tmccormi** [comment]
unclear what kind of note you would put on a single service code.  What is the clearing house limit on the note record?

**Comment by teryhill** [comment]
This is what they say. I personally think 50 should be plenty.

image

**Comment by tmccormi** [comment]
Sounds good then

**Comment by aethelwulffe** [comment]
The x-12 field limit is 80 for a NOC description in a SV1 segment.

**Pull request merged**
