### PR TITLE
UI enhancement in messages->show reminders->view log 

### PR DESCRIPTION
**Pull request by SoumyadeepJana**
Task 4 in [https://docs.google.com/document/d/1fq4NG_rnjMDACjjlFAZ15tIid4Rp6QnSyFHB-uc7tH0/edit](url)
1.Startdate and enddate fields left aligned.
2.Space added between the refresh button and the table that appears below the refresh button on clicking it.

### CODE REVIEW

**Comment by SoumyadeepJana** [comment]
Sure,will keep that in mind.

**Comment by aethelwulffe** [comment]
Let's finish this up when we get a final from @tmccormi

**Comment by teryhill** [comment]
Everyone is good with has 3 up votes I will merge

**Comment by tmccormi** [comment]
Adding the ?w=1 to the end of the URL turns on "ignore white space" diffs. 
https://github.com/LibreHealthIO/LibreEHR/pull/761/files**?w=1**

**Pull request merged**
