### PR TITLE
UI Enhancements done in Reports->Blank Forms->Superbill

### PR DESCRIPTION
**Pull request by SoumyadeepJana**
In Reports->Blank Forms->Superbill
Print button moved up and given blue bg color

### CODE REVIEW

**Comment by Trodrige** [comment]
Hi, @SoumyadeepJana . Good work. It is important to open an issue, solve it and then do a pull request. Things are better that way. Not everyone knows about those "EHR UI enhancements" tasks I created. 
I'm happy with the work you've done(Not yet tested). Open a new issue with a clear title and description. They shouldn't be referenced from the "EHR UI enhancements" tasks.
You can start by changing this title here.

**Comment by teryhill** [comment]
@SoumyadeepJana could you do before and after screen shots?

**Comment by SoumyadeepJana** [comment]
@Trodrige  sure I will fix that

**Comment by SoumyadeepJana** [comment]
@teryhill I will provide it as soon as I get back home.

**Comment by SoumyadeepJana** [comment]
@Trodrige  Should I close this PR  and open an issue first then do a PR?

**Pull request closed without merging**
