### PR TITLE
Fixed Uncaught ReferenceError.

### PR DESCRIPTION
**Pull request by pri2si17-1997**
Signed-off-by: Priyanshu Sinha <pksinha217@gmail.com>

### CODE REVIEW

**Comment by pri2si17-1997** [comment]
Hello @teryhill, when we browse to `Reports->Clients->List`, then this exception occurs. So i have made a change to it. Please do have a look at it and let me know if anything i'm missing.

Here is the snapshot of the same : 
screenshot from 2017-03-10 17-40-28

**Comment by teryhill** [comment]
@pri2si17-1997  you need to remove the jquery line from line 375 It was at the bottom of the file

**Comment by pri2si17-1997** [comment]
Hello @teryhill , I removed that line. Thank's I missed that line yesterday.
Please let me know if anything else required.

**Comment by aethelwulffe** [comment]
Terry, please run this as a review and approve etc...

**Pull request merged**
