### PR TITLE
"Issues" -vs- "Medical Problems" - renamed

### PR DESCRIPTION
**Pull request by alpinus4**
### Renamed _Issues_ to _Issues and encounters_

Before:

After:

### and _Medical problems_ to _Issues_

Before:

After:

#### Also removed unnecessary `<title>` tags

Fixes: https://github.com/LibreHealthIO/LibreEHR/issues/917

### CODE REVIEW

**Comment by alpinus4** [comment]
@tmccormi

**Comment by aethelwulffe** [comment]
Sorry @alpinus4 , could you pop in before/after screenshots?
I still think that "popups" is a terrible tab title.

It seems like "Popups" actually means widgets that interact with the *current patient*.  To me, I think they should be in the patient/client tab, or next to it, or arranged some other way.  "Popups" doesn't say anything.  Most folks will never even look in that tab.  Doesn't seem like anything they would want.

So:  Some of the "Popups" like the "Issues" one should probably belong to "Patient/Client".  Frankly, so should barcode and a number of other things...though they are less commonly used, but in a sub-menu.

Now the name of "Issues".  Frankly, these are basic medical charting items, but "Chart" means different things to different people.  I think that "Health Factors" _might_ be a good name option.
I would like to hear a clinical opinion on this. @yehster 

All the same @alpinus4 good job so far.

**Comment by teryhill** [comment]
Screen Re-Design for better work flow!!! lets go that route.

**Comment by aethelwulffe** [comment]
@alpinus4   It would be really nice if we can tweak this into a real workflow improvement.
I will come up with some menu json suggestions if you like, but I bet you could make a few tab group changes and come up with something significantly better than it currently is.

Feel like doing that?  We could do it here or in a different PR.

**Comment by teryhill** [comment]
This could be a GSoC Project or one for @alpinus4 after GCI

**Comment by aethelwulffe** [comment]
@teryhill agreed.

All the same, I think that "Issues and Encounters" is not the right name for this feature.

**Comment by alpinus4** [comment]
@aethelwulffe Sorry for the delay, whole day yesterday worked on _managing encounters webcomponent_.
I added _Before_ and _After_ screenshots :)
And... 
> Feel like doing that? We could do it here or in a different PR.

Hmm I think .. yes.. I can do it after GCI, ... but also want to work on my own projects, so it won't be a work as intense as during GCI...

**Comment by alpinus4** [comment]
@aethelwulffe Renamed.
#### After:

**Pull request merged**
