### PR TITLE
Update README.md and INSTALL.md

### PR DESCRIPTION
**Pull request by Kachachan**
changelog:

For README.md:
1. Edited lightly for clarity and consistency.

For INSTALL.md:

1. Reorganized the document to make more logical sense (I think. Please see if you disagree.) and cut down on redundancy. The problem was that the original document was split into two parts: one for installation on both Linux and Windows systems, and one for installation on Windows systems only. Not only is this a bit redundant (because instructions for Windows systems were mentioned in both sections), the installation instructions only actually diverged at the beginning, too; after you got setup.php running, the steps to install the software for both OSes were practically the same. Thus, we were being quite tautologous, as we were repeating the same information twice -- once in each section. To combat this, I decided it was probably a good idea to split the instructions into Linux-specific and Windows-specific sections at the beginning only, and combine the rest of the redundant instructions into one section, "Setup", together. 

I think this should improve upon the clarity of the document quite a bit. For example, when I first read the original document, I thought I needed to install MariaDB, Apache, PHP, and XAMPP for Windows; in reality, all I needed was XAMPP -- the other three came with it. 

2. Fixed a bunch of typos and grammatical errors.

3. Added mention of WAMP being a possible alternative to XAMPP (In the original document, in the section that had instructions for both Linux and Windows systems, WAMP was mentioned, but in the Windows section, WAMP was neglected altogether. Not sure what happened there.)

4. Added mention of the user having to move LibreEHR to the root folder (htdocs or www). The original document did not mention this, and I, a user who had never used XAMPP before, had to spend quite a while figuring out how to get it to work.

5. The Apache configuration files for windows is not at xampp\apache\conf\httpd.conf, but xampp\apache\conf\original\httpd.conf. I updated the file accordingly.

### CODE REVIEW

**Comment by Kachachan** [comment]
@aethelwulffe Here are the changes to the English installation files that I mentioned in [PR 874](https://github.com/LibreHealthIO/LibreEHR/pull/874) yesterday. They are quite a significant departure from the files we had previously, so please see if you think my changes make sense. If not, I could revert them to where they were before.

If this PR is approved, I will get to work on updating my Thai translation as soon as I can, and will tag you on that PR when it is done.

Thanks!
Kachachan Chotitamnavee

**Comment by Kachachan** [comment]
Huh. I thought I caught all of it. I'll give it another look over. Does the content seem fine, though?

**Comment by aethelwulffe** [comment]
Luckily, I don't see any of the other common errors like using an apostrophe in a possessive pronoun (its vs it's).  Needs checking though.

**Comment by aethelwulffe** [comment]
The content seems fine, but I read it better when I pull and run the MD file...which I will do after you have had some nice happy quiet time with the spellcheck :)  We would not my picky sensibilities coming into play when I am looking at technical content.  I have to actually follow the instructions to validate a technical writing document, so the review of this is _not trivial._

**Comment by Kachachan** [comment]
Right. I didn't actually make many changes to how it is written, I just reorganized and reordered the document a bit. I see how that might create confusion, though. 

It looks like I might've forgotten to save the file after I did my first spellcheck.. there's a bunch that came through somehow. I'll give it another read through right now.

**Comment by Kachachan** [comment]
Here's another thing I had a question on. The original docs said:

> The LibreHealthEHR release archive should be named as follows:
librehealthehr-<version>-release.tar.gz -or- librehealthehr-<version>-release.zip.

However, when I go onto the releases page on the github repo, the files seem to be named differently. The latest one is LibreEHR-REL-2_0_0.zip. I have left this line as is, because I wasn't sure this repo is where the release archives were being taken out of, but I am not sure at all. Should I change the naming scheme?

**Comment by aethelwulffe** [comment]
@tmccormi @teryhill please help us with the release name quandary above.

**Comment by Kachachan** [comment]
I swear I've already made all these corrections before.. I think I must have messed up somewhere during my reversion process :P

In any case, please take a look at the file now and see if there is anything you think merits change.

**Comment by aethelwulffe** [comment]
HaHa....yeah, it was a mess.  
good job in the end.  Don't you hate editing? :)
  I have to get some work done now, but I am sure you will have a full review after your sleepy-night-night time.

**Comment by Kachachan** [comment]
@aethelwulffe Any updates to this PR so far? Thank you!

**Comment by Kachachan** [comment]
@teryhill It looks like you just submitted another commit that reverted some of the changes I made [here](https://github.com/LibreHealthIO/LibreEHR/pull/899/commits/eb5208cf4b49623da1b8856ba31a3775919de40d). 

Did you revert it because you thought my changes (on the left of that particular commit) were bad? I'm afraid I don't quite understand. Sorry.

Thanks!
Em

**Comment by teryhill** [comment]
@Kachachan I was attempting to resolve the conflicts , sorry

**Comment by teryhill** [comment]
@tmccormi can you reverse my commit on this. I was attempting to clear the conflict and got the wrong information.

**Comment by aethelwulffe** [comment]
@tmccormi  TOOOONNNNYYYY!!!!!!

Puh-Leez fix this Pee Arrr.  Wee kant kodez.

If you would so kindly revert the terry commit and see to getting this merged up, we would all appreciate it greatly.
Good job @Kachachan

**Comment by tmccormi** [comment]
I am entirely unclear what you need me to do.  I'd just close this PR and resubmit one with corrected data.  It has not be merged.

Regarding "zip/tar" file names.  GitHub generates names based on the repo name/branch name  No control of that.  Do we care?

**Comment by Kachachan** [comment]
On the issue of "zip/tar", it was just that the naming convention in the INSTALL.md file was different from Github's methodology. I could simply change the text in INSTALL.md if you want.

I'll create a new PR in a moment.

**Pull request closed without merging**
