### PR TITLE
Fixed css property.

### PR DESCRIPTION
**Pull request by pri2si17-1997**
Signed-off-by: Priyanshu Sinha <pksinha217@gmail.com>

### CODE REVIEW

**Comment by pri2si17-1997** [comment]
#196 

Hello @teryhill @aethelwulffe I have made some changes in the css  file mentioned in above issue. Please check it let me know if anything needed.

**Comment by teryhill** [comment]
@pri2si17-1997  What does this change exactly? You are working with Old Guy's 8^)

**Comment by pri2si17-1997** [comment]
@teryhill I am not sure what this change will do. But when I looked at issue #196, I browsed to those files. There I found syntax error(`*` before css property). Also i found  `zoom`  was used which is a non-standard css property, so i changed it to `transform : scale()`. So i thought to change that. 

http://stackoverflow.com/questions/4563651/what-does-an-asterisk-do-in-a-css-property-name
https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

**Comment by pri2si17-1997** [comment]
@aethelwulffe Yes `css/demo_table.css` called in following pages:
`/interface/tags_filters/views/layouts/patients_tags_layout.php`
`/interface/tags_filters/views/layouts/tags_layout.php`
`/interface/tags_filters/views/layouts/filters_layout.php`
`/interface/themes/rtl.css`
`/interface/main/finder/dynamic_finder.php`

**Comment by aethelwulffe** [comment]
It's just an odd name, and...well...this project has a history of including unneeded files in packages.  Thank you for taking care of these irritating css errors.  There was an issue that listed every error in my logs, but that is long gone I think...

**Comment by aethelwulffe** [comment]
Getting rid of asterisks is good.  The non-standard Firefox bit...so long as it is currently supported is fine I suppose, but should be commented as non-standard blah, blah, blah, if you deem it might be a future issue.

**Pull request merged**
