### PR TITLE
Print button prioritized in Reports->Blank Forms->Superbill  

### PR DESCRIPTION
**Pull request by SoumyadeepJana**
Fix to issue #825 
1.Print button moved up
2.Background color of print button has been changed to make it more consistent.

Before:

After

@Trodrige  I opened an issue and fixed it.Does this seem okay?

### CODE REVIEW

**Comment by Trodrige** [comment]
@SoumyadeepJana this is great. Just a small change, can you put the "Print" button on the same level(horizontally) with "Superbill/Fee Sheet". Don't change the vertical position. This is good!

**Comment by SoumyadeepJana** [comment]
@Trodrige  sure will do that.

**Comment by teryhill** [comment]
@aethelwulffe can you look at this and give a thumbs up or down so @tmccormi can merge

**Comment by tmccormi** [comment]
Ping @aethelwulffe ...

**Comment by aethelwulffe** [comment]
Having issues pulling down the branch...guess I should switch to ethernet...

**Comment by aethelwulffe** [comment]
Resolve conflicts...then we can merge

**Comment by aethelwulffe** [comment]
OK, your conflict is in the dated_reminders_log stuff.  You added  `style="margin-left:1px`  to a line, and that whole section had been converted to bootstrap.  It also has that change there, introduced in another PR #916 I believe.  I have looked into it a little more, but the changes are making my eyes hurt, as I have to look at the raw on your branch, look at the blame on the LibreEHR master, and look at the conflict resolution web editor at the same time.
-So, if you would please update this branch and rework it a wee bit, we can include these changes...and get on track to actually merging things in order and working the OLDEST PR's FIRST.

**Comment by aethelwulffe** [comment]
@SoumyadeepJana Could you please resolve the conflicts in this file.  I would like to get it merged soon please.

**Comment by tmccormi** [comment]
Should I just handle this?   @SoumyadeepJana seems to be missing ...

**Comment by teryhill** [comment]
Yes Please.

**Comment by tmccormi** [comment]
I fixed this and pushed it directly to master.

**Pull request merged**
