### PR TITLE
Fix #414: 'Back to Patient' button on screens linked from demographics

### LINKED ISSUE #414: 'Back to Patient' button on screens linked from demographics
Hi Folks-

What do you think about adding that 'Back to Patient' button to the screens linked to at the top of the summary screen?

History | Report | Documents | Transactions | Issues | Ledger

'History' has 'Back to Patient' and I see Issues has 'Back'.  I think that's a very worthwhile button to have, and it'd be good UI continuity to put it on the others.  And make that 'Back' -> 'Back to Patient'...

lehr-hx-btns

### PR DESCRIPTION
**Pull request by apooravc**
Fixes #414 
Added "Back To Patient" button on Report | Transactions | Issues | Ledger, on demographics screen for patient.

Preview:
Report
report

Transactions
transactions

Issues
issues

Ledger
ledger

Questions:

- Transaction screen has a "cross"/close button and it opens as a window over demographics screen. I think there is no need to add button here or if added, it should close the transaction window? 
Preview:
transactions2

- I didn't add the button to Documents because there is also another way to go to Documents screen, the 'Misc. > New Documents' route. So should there be something which checks which route user took and then add the button?

One way to see the changes _locally_ would be as follows:
1) Clone my repo via `git clone https://github.com/apooravc/LibreEHR.git`
2) After cloning, only the master branch would be available locally. Enter `git checkout -b add-back-button origin/add-back-button` or `git branch add-back-button origin/add-back-button` to get the branch _add-back-button_ locally.
3) The changes could then be seen on respective screens.

@aethelwulffe @teryhill Please have a look.

### CODE REVIEW

**Comment by aethelwulffe** [comment]
Funny how History isn't part of demographics, or listed under demographics, but is rather a separate sort of item.
Under issues, you can access surgery and dental issues, but everything else (allergies etc...) already has it's own widget.  

For documents, pass a $from_page value to the URL.  As a matter of fact, we can do that in a lot of places.

**Comment by apooravc** [comment]
What about "Transaction" widget? Does it also need the back button?

**Comment by aethelwulffe** [comment]
Transaction window can just be closed.  It is fine, as the background iframe never goes away.

**Comment by apooravc** [comment]
Removed button from Transaction screen and added button to Documents (thanks to @teryhill ).
Used `(int)$GLOBALS["_GET"]["patient_id"]` to figure out when the user navigates to Documents screen via route `Misc. > New Documents`, which would give `0` value.

**Comment by aethelwulffe** [comment]
I'll test after things calm down here!

**Comment by apooravc** [comment]
@teryhill Could you also please review this to check if it can be merged?

**Comment by teryhill** [comment]
@aethelwulffe  bump

**Pull request merged**
