### PR TITLE
Fix edit history patient bug

### LINKED ISSUE #881: Can't edit history
**Steps to Reproduce**
1. `Patient/Client` --> `Add New/Search` --> select any patient
2. Click on History
3. Click on Edit.
4. Try and change Patient's history, observe errors.
libreehr8

**Reproduction Rate**: 5/5

**System Specs** LibreHealth EHR v2.0.0, Chrome Version 63.0.3239.84 (Official Build) (64-bit), Windows 10 Version 10.0.14393 Build 14393

### PR DESCRIPTION
**Pull request by prabhakarpd7284**
Fixes #881 
- problem is solved by adding an extra column **usertext11** in `history_data` table.

You need to recreate your `history_data` table from `database.sql.`

### CODE REVIEW

**Comment by teryhill** [comment]
@aethelwulffe  

image

**Comment by aethelwulffe** [comment]
@teryhill thanks.
That file needs to pretty much go away in any case.  That is an old test file.  I can mod it if it seems like it is still applicable.

**Comment by teryhill** [comment]
@aethelwulffe  take a look at the history file. The usertext11 field id currently being used by Risk Factors. @prabhakarpd7284 this needs to be fixed in the file and in the layouts. The field needs to be called risk_factors or something meaningful.

**Comment by aethelwulffe** [comment]
Exactly...

**Comment by prabhakarpd7284** [comment]
I'll make the necessary changes.

**Comment by aethelwulffe** [comment]
Thanks man!
-Art

**Comment by prabhakarpd7284** [comment]
@aethelwulffe @teryhill 
I have made the corresponding changes after cross checking all data.

Also please have a look at `ippf_export.php`. It uses column names in the query which doesn't exist in any table like usertext12, usertext13, etc. 
ipff

I think it has become a redundant file.

**Comment by aethelwulffe** [comment]
ippf_report IS AN UNNEEDED file.  In another PR, anything named `ippf` can be removed from the system.

**Comment by prabhakarpd7284** [comment]
I think this issue is done then.

Also about the `ippf` redundant files, is there any already open issues? 
If not, then I will open an issue and then make the PR.

**Comment by aethelwulffe** [comment]
No open issues AFIK.

**Comment by aethelwulffe** [comment]
This PR should only wait one more day before getting reviewed or merged.  PEOPLE:  Please do some branch pulls on this and other minor PR's, test, and let's keep on track.

**Comment by prabhakarpd7284** [comment]
Is there still any issue with merging this PR ?

**Comment by aethelwulffe** [comment]
There are no problems.  @teryhill @tmccormi @Trodrige  SOMEONE please review!

**Comment by teryhill** [comment]
Need to make a mental note to not use the usertext fields for this @aethelwulffe  any more.

**Pull request merged**
