### PR TITLE
MyISAM engine declarations

### PR DESCRIPTION
**Pull request by aethelwulffe**
Remove MYISAM engine declarations

### CODE REVIEW

**Comment by teryhill** [comment]
Instead of deleting it should you replace it with InnoDB? Just asking, not sure it matters.

**Comment by tmccormi** [comment]
Yes it should have the INNODB declaration, otherwise it will default to whatever the database was created as. Not an issue with "default" setup but could cause issues if someone manually pre-creates the DB and doesn't set the default INNODB.

Also some of the tables were not working in INNODB to to unsupported types, where those issues address? @yehster know the most about that from the Peace Corps project.

**Comment by aethelwulffe** [comment]
https://mariadb.com/kb/en/library/converting-tables-from-myisam-to-innodb/
I use the above bits of advice.
These forms are actually fine either way.  They have nothing special, and have only a single key.  It is listed first, declared specifically, and is otherwise well behaved.
I will specify the engine.

**Comment by tmccormi** [comment]
Nice resource.

**Comment by aethelwulffe** [comment]
Added a commit.

**Pull request merged**
