### PR TITLE
EXPERIMENTAL Video chat Testbed

### PR DESCRIPTION
**Pull request by aethelwulffe**
WebRTC components for testing within LHEHR and Patient Portal

### CODE REVIEW

**Comment by aethelwulffe** [comment]
untitled

**Comment by SoumyadeepJana** [comment]
@aethelwulffe  I would like to work on this one.

**Comment by aethelwulffe** [comment]
@SoumyadeepJana 
BY ALL MEANS!!!
There is a lot to figure out that I don't know yet.
1.  Does the application actually need a STUN or TURN server when it is a single page application?
2.  What is the best way to integrate video chat into the patient portal as a telehealth tool for counseling and the like, as well as intercom-like functions between staff?
3.  Integrate or supplant the Portal chat tool (needs "who is online" functions like that)?
4.  Pick a feature to develop first (video), then add others, or do a full package module all at once?
5.  Use in iFrame, or embed in modal?

Capabilities that are possible:
1.  Typical telehealth voice and video conferencing.
2.  One-on-one or group communication for meetings or counseling.
3.  Take still images for clinical evaluation, progress note addenda, or even allow the patient to save their own photo for their demographics record.
4.  Chat and messaging with complex behavior.
5.  Recording sessions.
6.  Streaming.

Additional things that would be needed:
1.  Configuration UI's.
2.  Configuration documentation (particularly if STUN and TURN servers are wanted or needed).
3.  Assessment and deployment of something like https://github.com/coturn/coturn should the above be required.

So far, I have only evaluated this code (stripped from the project described in the README) with LAN connections.  Obviously, I have not done much yet.  A real .js developer _in conjunction with some good clinical what-if usage cases_ would doubtlessly do a better job than I in short term.

**Comment by aethelwulffe** [comment]
The EHR needs a "who is online" widget in ANY CASE...

**Comment by SoumyadeepJana** [comment]
@aethelwulffe This will be a great inclusion to the module as there will be many test cases where this functionality will be needed.
1.Patients can contact their clinical guidance immediately in case of emergency without physically visiting the clinic.
2.Storing pictures of potential affected visible diseases could be beneficial for both the clinical community, which can be referenced for future use(maybe Machine Learning).

I will analyse the techinal requirements and get started.

**Comment by aethelwulffe** [comment]
@SoumyadeepJana 
Thank you!  This seemingly common now-adays functionality has a lot of potential in this setting.  This is going to be very very important...

**Comment by MigDinny** [comment]
@aethelwulffe that photo was creepy

(<title></title> is nice)

**Comment by aethelwulffe** [comment]
@MigDinny Thank You!  I have done a good job then!  I was saying something along the lines of "Muahahahahahaha!" as I hit [prt sc].

**Comment by aethelwulffe** [comment]
I have no idea why it thought that the tab was "Message and Reminders".  That is not in the document itself.  I have not got to dealing with that yet anyway.

**Comment by MigDinny** [comment]
@aethelwulffe ahaha, those blue eyes are f****** scary

about the "message and reminders", I know that it can be changed on the HTML code... I previously worked on EHR and realized that there is an element that has that string which controls the tab name

**Comment by aethelwulffe** [comment]
I am told the official name of my eye-color is "Idiot Blue".

**Comment by aethelwulffe** [comment]
Has anyone else successfully tested this (on LAN at least)?

**Comment by teryhill** [comment]
@SoumyadeepJana look at the patient portal dashboard , that might be a good place to put a "Hook" for this.

**Comment by teryhill** [comment]
@SoumyadeepJana Are you still interested in this.

**Comment by aethelwulffe** [comment]
Gonna close this PR.  It ain't going anywhere for now.

**Pull request closed without merging**
