### PR TITLE
Remove the entries for role based menus till an acceptable editor is in place

### PR DESCRIPTION
**Pull request by teryhill**
Remove the entries for role based menus

### CODE REVIEW

**Comment by tmccormi** [comment]
Any chance these menu items can be added to the JSON file or is that already done? @teryhill

**Comment by teryhill** [comment]
I am not sure what you are asking. The menu items should be in both files since you and Art don't use the Tables.

**Comment by tmccormi** [comment]
The Role based menu items is what I was asking about, specifically

**Comment by teryhill** [comment]
I don't know . Dr Ray did it based on the tables not the Json file. Just put his commit up there.

**Pull request merged**
