### PR TITLE
HTML5 cms1500 form

### PR DESCRIPTION
**Pull request by aethelwulffe**
html conversion of a cms1500 to use as the basis of an interactive
graphical form.

### CODE REVIEW

**Comment by aethelwulffe** [comment]
having wicked issues getting time to work on this, yet getting hounded about it daily...

**Comment by teryhill** [comment]
We need to evaluate the current fee sheet and see what fields we need to add to make this happen and put them in a new include file for us to start working out of to make our changes

**Comment by aethelwulffe** [comment]
We have no separate repo for general "stuff" anymore.  We lost that in the change-over.  Since this isn't going into contribs, and we don't have a dev resource spot, It goes no-where.  I am going to drop this request and keep it on my machine in a nice dark hole.

**Comment by teryhill** [comment]
can you zip up a copy and send it to me?

**Comment by aethelwulffe** [comment]
Sure, sending your way...I think I can restore my local branch still.

**Pull request closed without merging**
