### PR TITLE
Added CSS and common used files.

### PR DESCRIPTION
**Pull request by teryhill**
Added CSS and common used files. @aethelwulffe

### CODE REVIEW

**Comment by teryhill** [comment]
@aethelwulffe you need to merge this

**Comment by teryhill** [comment]
Apparently some files using the css function of this are already in the code base from a previous commit. I am committing this now.

**Comment by aethelwulffe** [comment]
Ok OK...You beat me by 13 seconds...

**Comment by aethelwulffe** [comment]
Sorry, I have been dealing with the CMS github stuff...https://github.com/CMSgov/qpp-submissions-schema/blob/master/schemas/submissions.xsd

**Pull request merged**
