### PR TITLE
Fixed JQuery exceptions.

### PR DESCRIPTION
**Pull request by pri2si17-1997**
Signed-off-by: Priyanshu Sinha <pksinha217@gmail.com>

### CODE REVIEW

**Comment by pri2si17-1997** [comment]
Hello @teryhill @aethelwulffe ,

There was JQuery exception in `Administration->Addr Book` as follows : 
screenshot from 2017-03-15 01-04-20

After that clicking on `Add New` produces following exception:
screenshot from 2017-03-15 01-04-44

Now its working fine on my machine.

Please do look at it and let me know if any other changes required.

**Comment by teryhill** [comment]
I think the issue is that abook_type is undefined so it is throwing an exception. The check you are using does not make sense to me. One thing I do is hard code the variable and see if my test , if statement, works.

**Comment by pri2si17-1997** [comment]
@teryhill . 
Exception shown in first screenshot is due to missing jquery plugin. So I added it along with necessary fancybox js.

In second screenshot `abook_type` was not defined. In the code it was mentioned to display according to type selected. If we look at the line `typeSelect("<?php echo attr($row['abook_type']); ?>");` it gets the value selected. It can be checked in console. So I compared that value in if condition, as `abook_type` is not a variable declared but is one of the column of `users` table. 

This was what my understanding was while making this change. Please let me know if i'm wrong.

**Comment by pri2si17-1997** [comment]
Hello @teryhill 
Now you please check it and let me know if anything else needed.

**Comment by teryhill** [comment]
Looks Very good  @pri2si17-1997

**Pull request merged**
