### PR TITLE
Added a new cursor icon when hovering patient

### PR DESCRIPTION
**Pull request by MigDinny**
When hovering over patient's last name on Patient Finder the cursor changes to a 'refresh' cursor to warn the user that he's switching patients.

No cursor was defined on style_tan before and it should be.

If, for some unexpected reason, the asset isn't loaded, 'default' is loaded instead.

The icon has a transparent background and is 20x20 and must remain with those characteristics.

I took the icon from here:
https://icons8.com/icon/pack/free-icons/win8

I don't know how to attribute correctly this asset, so please, correct me if I did anything wrong.

Tried to use font-awesome, jwarby and other services but none of them perfomed well on this task.

This is my task for GCI 2017: https://codein.withgoogle.com/dashboard/task-instances/5280206610759680/

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Attribution needs to happen in the code.  You're breaching the license requirement as it stands.

**Comment by aethelwulffe** [comment]
sprite0
Here...homemade...no attribution needed.
If you can't roll your own, just tell me what you would like, and I will produce it.  If you like two chasing arrows in blue or something, I can do that too.  If you want a smooth look, I will make this large and do a high-fidelity scaling.  This is modeled after the refresh in FireFox as well as a million other refresh icons over the decades.

**Comment by MigDinny** [comment]
@aethelwulffe thanks! I'm using your asset now. I commented with your name there. An icon with 2 arrows like the old one would be preferable, but it's ok as it is now.

**Comment by Trodrige** [comment]
@MigDinny this looks good to me. Great job here!

**Comment by aethelwulffe** [comment]
twoarrow
There is another way-two-quick lumpy icon.
Gotta get used to spriting really small stuff again.  There is...no room for error when doing such tiny stuff.

**Comment by MigDinny** [comment]
@aethelwulffe done. Check the new commits.

**Comment by MigDinny** [comment]
@Trodrige Thanks! I tried to use a different method for this task but it didn't work and produced a lot of bugs, which weren't a good option. I tried to use a jQuery plugin to select the css class and change the cursor when hovering it but that jQuery plugin only could be run within main.php (and that would create bugs because those classes weren't even rendered when accessing main.php). A lot of bugs would be produced and I finally decided to use this simple method.

**Comment by aethelwulffe** [comment]
If you like, you can continue to tweak this, but it is at a "good enough" state to me.  It can be merged once we get the "three eyes" review.

**Comment by teryhill** [comment]
@MigDinny can you tell me what I am suppose to be seeing ? A screen shot would be helpful.

**Comment by aethelwulffe** [comment]
@Trodrige 
Please do an official review approval, and if you can, merge.
If you can't merge, I put it up to vote that we grant you those permissions
@teryhill 
@tmccormi 
@nileshprasad137 
@pri2si17-1997 
@azwreith 
We should have a team permissions review item at the next meeting.

**Comment by Trodrige** [comment]
I think we should use another icon. Something solid black. @MigDinny this is great.

**Comment by aethelwulffe** [comment]
@Trodrige 
Actually, I was thinking about just a transparent grayscale.
It is totally easy to colorize icons and images with either CSS or various JS resources.  css/html5 seems to be perfectly capable now-adays.
I'd like to have nothing but transparent grayscale icons...

**Comment by Trodrige** [comment]
If the icon looks good, then we go for it. I think the current one should be changed.
@aethelwulffe maybe @MigDinny can still touch this.

**Comment by tmccormi** [comment]
I'm ok to merge this..  however a simple search of refresh icon under creative commons license reveals tons of these ..

https://www.google.com/search?tbm=isch&q=creative+common+refresh+icon&chips=q:creative+common+refresh+icon,online_chips:icon+svg&sa=X&ved=0ahUKEwiUve_By_HXAhUEKWMKHXvmDpUQ4lYIMCgK&biw=1763&bih=925&dpr=1

**Comment by tmccormi** [comment]
Like this one from wikimedia ..
refresh_icon

**Comment by tmccormi** [comment]
Here's a set with vector formats
[Refresh-02.zip](https://github.com/LibreHealthIO/LibreEHR/files/1529230/Refresh-02.zip)

**Comment by tmccormi** [comment]
Do a new pull if you would like to update the icon some more ...

**Pull request merged**
