### PR TITLE
Some menu and globals cleanup

### PR DESCRIPTION
**Pull request by teryhill**
Some menu and globals cleanup. Took out some left nav specific stuff (tall nav, hide menu etc). Added more checks for existing globals.

### CODE REVIEW

**Comment by teryhill** [comment]
@tmccormi I noticed there was no entries for the new crop code in the json file , is this an over site or is it intentional?

**Comment by tmccormi** [comment]
Kevin created that data from Left Nav, so it should have been there.  It's not supposed to show if the Global is not enabled.  I have not looked at it since I have no production LibreEHR with NewCrop.  I'll open an issue for it.

**Comment by aethelwulffe** [comment]
Well cool  OUt of my hands (woo-hoo!)

**Comment by aethelwulffe** [comment]
Branch still live.

**Pull request merged**
