### PR TITLE
Update README.md and INSTALL.md

### PR DESCRIPTION
**Pull request by Kachachan**
Followup on PR #899

### CODE REVIEW

**Comment by Kachachan** [comment]
@tmccormi, sorry, I'm not too familiar with GitHub. It looks like the edit that @teryhill had made (and we want to revert) is still here even after I had made a new PR, like you asked me to. 

Please advise? Should I go into the files and fix each changes manually?

**Comment by aethelwulffe** [comment]
I would proceed with the web editor link right here to fix these changes.
-Sorry it took me so long to get a review in.  Thank you very much!

**Comment by aethelwulffe** [comment]
This is an excellent document.  I looked at the conflict though, and it appears that the whole file is in conflict with master.  Would someone please try to figure out what happened here?  Documentation edits should not take weeks and be this hard.

**Comment by Kachachan** [comment]
The conflicts exist because the documentation was edited after I had submitted this pull request. So my PR, that had edits based on the original INSTALL.md, became out of date. I'm currently busy with school, but in a few days I can try and sort things out.

Sorry for the long delay about this.

**Comment by teryhill** [comment]
This branch has conflicts. These file have other updates pending. Closing this one to add the others.Sorry

**Pull request closed without merging**
