### PR TITLE
[ENHANCEMENT]: Updating the ui of flow board. Removing the style attr…

### PR DESCRIPTION
**Pull request by sandipbhuyan**
In flow Board UI  the select tag for status section was not aligned with other select tag. This was because inline styling has been added there. So i removed the style attribute through jquery.
**Before**
screen shot 2018-02-18 at 4 15 46 pm

**After**
screen shot 2018-02-18 at 4 15 35 pm

### CODE REVIEW

**Comment by pri2si17-1997** [comment]
@sandipbhuyan create new branch, make changes into that and then raise PR against master branch.

**Comment by sandipbhuyan** [comment]
@pri2si17-1997 do I need to remove my second commit and make another PR for it ??

**Comment by aethelwulffe** [comment]
Uh, these look OK.  I believe we can squash and merge fine.  That OK @pri2si17-1997 ?

**Comment by aethelwulffe** [comment]
@teryhill You good with this?  Looks like we are getting some PR's with duplicated efforts, so we should try to merge these either by quality priority or date priority.

**Comment by teryhill** [comment]
It is not what I wanted. But I guess it will do till that get here.

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 21, 2018 at 3:24 PM, Art Eaton<notifications@github.com> wrote:   
@teryhill You good with this? Looks like we are getting some PR's with duplicated efforts, so we should try to merge these either by quality priority or date priority.

**Comment by aethelwulffe** [comment]
Closing this on request.

**Pull request closed without merging**
