### PR TITLE
no stomp menu experiment

### PR DESCRIPTION
**Pull request by aethelwulffe**
set all menu items to unique menu id's
This pull request is for discussion, but the branch is for tinkering and possibly a merge after some review etc...

### CODE REVIEW

**Comment by tmccormi** [comment]
I'm not seeing what I expected, still lots of things in the Reports menu that step on the previous report.  I'm going to recheck my install, I might not have gotten the code change I expected

**Comment by aethelwulffe** [comment]
Well check it, and lemme know, cause maybe I left some changes out of the commit or some other craziness.

**Comment by aethelwulffe** [comment]
An even more important bit is the attaching tabs to the form element (instead of aligned left), increasing the size of the tab controls (and tabs) and making the tab size configurable resizable.  After that is still the formatting of the contents of tabs.
  Right now, I wouldn't recommend the layout for regular use.

**Comment by tmccormi** [comment]
I think a simple short term solution would be to allow there to be a configurable limit of the number of tabs in the foreground.  Default to 3 max.

**Pull request closed without merging**
