### PR TITLE
Create Installing-on-Linux

### PR DESCRIPTION
**Pull request by YourDoge**
Created instructions for installing on Linux

### CODE REVIEW

**Comment by robbyoconnor** [comment]
There's already a document on how to install this on Linux. The task is to find the gaps in the existing documentation.

**Comment by aethelwulffe** [comment]
Did you do a PR for your php XML extension thingie?

**Comment by tmccormi** [comment]
@aethelwulffe if you are talking to me, I updated and merged minor addition to INSTALL.md for php xml, yes (#863)

**Comment by aethelwulffe** [comment]
@tmccormi gotcha.

**Comment by aethelwulffe** [comment]
No response on this PR.  closing.

**Pull request closed without merging**
