### PR TITLE
fix to get AD to run

### PR DESCRIPTION
**Pull request by teryhill**
I missed this in testing #400

### CODE REVIEW

**Comment by teryhill** [comment]
These will fix the AD issues. I tested them on a clean install

**Comment by tmccormi** [comment]
OK,  I'll do a patch update of the release.  I think I'll wait a bit and see if there are other patches to do first though.

**Comment by aethelwulffe** [comment]
Note, I am not authorized to merge pull requests on this repo.  If that is how it is, that is fine, just making sure everyone knows.

**Comment by aethelwulffe** [comment]
Oh, no.  We just shifted to master, didn't we?

**Comment by tmccormi** [comment]
I had locked the master branch.   I'll switch the user access a back around shortly

**Pull request merged**
