### PR TITLE
Temporary Fix for #860 Patient Search

### LINKED ISSUE #860: Can't search patient
Open Patient/Client ==> Add New/Search. Then type some information about any existing patient and click search. And then you see this:

can t_find_patient

### PR DESCRIPTION
**Pull request by teryhill**
This is a temporary fix till art can fix it with the pqrs stuff. It looks like he had an older version of the file. I used one from a Feb 2017 version of the code. This will fix #860

### CODE REVIEW

**Comment by teryhill** [comment]
@tmccormi  This will fix #860 is in the description.

**Comment by teryhill** [comment]
Before

image

After

image

**Comment by tmccormi** [comment]
Right, along with a bunch stuff that should just be a comment not a commit description.  I'm pedantic about this stuff, I know, someone has to be :-)

I'm going to change the description...

**Comment by teryhill** [comment]
@tmccormi Thanks  Keep me straight

**Comment by tmccormi** [comment]
Should I wait on a 2nd review?

**Comment by teryhill** [comment]
Rules are 2 thumbs up before the trigger can be pulled and you can't thumbs up your own stuff.

**Comment by tmccormi** [comment]
I'll see if I can test it, right now I have no test data or site configured.   I just rebuilt my dev system.   getting that taken care of this evening and tomorrow.

**Comment by aethelwulffe** [comment]
I took yesterday off.
Going to look at this now.  I didn't realize we were still using the old patient search tool at all.

**Comment by tmccormi** [comment]
Closing the pull in favor of Art's solution.

**Comment by aethelwulffe** [comment]
I was sick, didn't get this attended to, and will be moving the MIPS stuff elsewhere anyway, so I am merging this...as it is really really needed immediately.

**Pull request merged**
