### PR TITLE
Added the ability for certain appointment status to be overbooked (if…

### PR DESCRIPTION
**Pull request by kchapple**
… appt cancelled, for example.) Find-availble will return those slots as available. This was added in such a way that a plugin can override the status array

### CODE REVIEW

**Comment by teryhill** [comment]
Looks good but should it be on a global switch and shouldn;'t the user be able to select the statuses they want to over book?

**Comment by tmccormi** [comment]
This is related to #513 - code (like the other hooks) should have no effect on the base application without the plugin.

**Comment by tmccormi** [comment]
It's a plugin: if they want to change the defaults they would need to provide (or acquire) the plugin to do that.   We do that so customer specific requests don't affect the baseline.

**Comment by teryhill** [comment]
Add what you want, I ave yet to see any benefit from this line of code it is putting extra code in the code base that is just there. It is your project @tmccormi

**Comment by tmccormi** [comment]
Once you learn how to use it you will see the benefit ... :-) It's our project, not mine ...

**Comment by kchapple** [comment]
@teryhill that's a better idea. thanks.

**Comment by tmccormi** [comment]
shall we close this a wait for a new one, then @kchapple ?

**Comment by tmccormi** [comment]
Deleting this one.

**Pull request closed without merging**
