### PR TITLE
Added the ability for certain appointment status to be overbooked (if…

### PR DESCRIPTION
**Pull request by kchapple**
… appt cancelled, for example.) Find-availble will return those slots as available. This was added to globals.

### CODE REVIEW

**Comment by tmccormi** [comment]
Related to #513

**Comment by tmccormi** [comment]
This one looks good to me..   the merge is against rel_101..  can pull if forward to master as well if that's OK.

**Comment by aethelwulffe** [comment]
Just explain the reasons, and I will try to come around.

**Comment by tmccormi** [comment]
This one is ordinary globals not plugin based..

**Pull request merged**
