### PR TITLE
Update README.md and INSTALL.md, and add Thai Translation for both.

### PR DESCRIPTION
**Pull request by Kachachan**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
I'm not sure how to review these tasks -- but we need to have someone who knows both languages well review this.

**Comment by teryhill** [comment]
@Kachachan This looks good, as much as I can tell. I do not speak Thai. I like that you corrected the English errors. I would like to ask if you would be willing , after GCI, to help with translating more of the project into Thai, I will get with the other Mentors to get your task approved.

 Can you tell me how long you worked on this?

**Comment by robbyoconnor** [comment]
I want to ensure that we don't get something that is translated using Google Translate.

**Comment by Kachachan** [comment]
@teryhill I will be glad to help translate more of the project.  It's actually quite fun.

I spent around 8 hours working on it in total (this included a lot of time making sure that I was comprehending the English instructions correctly. I had to install LibreEHR, and that took a while).

@robbyoconnor I assure you -- though I understand my word may not be worth much -- that I did not use Google translate here. I feel that it is an absolute abomination as well, particularly for technical pieces such as this. I understand your concern, though, and hopefully we have a Thai speaker around here who could help us review.

**Comment by robbyoconnor** [comment]
I have accepted their task. We should ensure we find a Thai speaker before merging this...that's just my opinion and @tmccormi and @aethelwulffe are allowed to override me as they run the show here, not me.

**Comment by teryhill** [comment]
@Kachachan thank you for your contribution. I look forward to having your help with the LibreEHR project.

**Comment by robbyoconnor** [comment]
I agree @teryhill -- I think @Kachachan is definitely one of the good students we have with us right now. This is not an easy task to do at all.

**Comment by Kachachan** [comment]
I think I messed up. I wanted these recent commits to be an entirely different PR. They're an unrelated issue. I just pushed them to my master branch, and apparently that was the wrong thing to do.

How do I revert this? :P

**Comment by tmccormi** [comment]
@Kachachan I can help you on the commit error issue.  The hint is to use "cherry-pick".   But let's discuss it on chat line instead of the pull request.  --Tony

**Comment by aethelwulffe** [comment]
Get this branch straightened out into a second PR, but once the content is straight, I suggest merging.  I put in a request for assistance from the TPAA.  That might be the best we can do.  I have looked for Thai physicians in my area, and have found none.  Vietnamese is not problem at all, but we do not have a large Thai community in my area.  South Florida, yes, but not here for some strange reason.

**Comment by Kachachan** [comment]
Here's another issue I have: with the recent commits I made (as seen above), I've made some extensive restructuring to the way INSTALL.MD is written. Assuming those changes are approved, I'd have to re-translate a non-trivial chunk of the original Thai translation that I made. 

Here's one way I think we can deal with this:
Tomorrow (Thailand Time, so in about 12 hours or so) I will close this PR, and create a new one that modifies the English files only. I will wait until that PR is approved, before working on modifying my translation to conform to the new English files. Then, I will submit my Thai translation as a second PR. 

Does that sound alright?
Hopefully the TPAA don't come checking just yet -- the commits I have mistakenly made messed the document up quite a bit!

**Comment by aethelwulffe** [comment]
I doubt the TPAA will be quick to respond.
I think your proposed approach makes good sense.  I will be ready for your changes when you do them (after nice sleepy time).

**Pull request closed without merging**
