### PR TITLE
Addresses #445, Adds a On-Demand Receipt

### PR DESCRIPTION
**Pull request by nileshprasad137**
This Pull request addresses #445 . 

receipt

Note: This PR may be currently labelled as `"WORK IN PROGRESS"` , as the receipt  added currently behaves very similar to the ledger itself , having a date range to print the payments. 
@aethelwulffe @teryhill Please have look at the format and recommend some changes if required. We need to figure out a way to print a statement from the ledger itself.

### CODE REVIEW

**Comment by nileshprasad137** [comment]
Thanks @aethelwulffe 

>  I am also curious as to the potential for such statements to be stored, recreated on demand, or even generated via a patient portal. 

I will surely look for these when I get some time.

**Comment by teryhill** [comment]
There is a version of the patient ledger in the patient portal so adapting this code to it should not be an Issue. I would like to see just one version of the patient ledger report program used for both Portal and the main core.

**Comment by aethelwulffe** [comment]
OK guys, what is the next step here?

**Comment by teryhill** [comment]
I got some changes I will send when I get back to the office.

**Comment by teryhill** [comment]
It would be good to have the facility information on the receipt. Get rid of the UAC Appl and UAC tot information. Add provider name. That ought to be good for now.

**Comment by nileshprasad137** [comment]
I would be fully back once my exams get over on 20th May. Till then, you all may make required changes.

**Comment by aethelwulffe** [comment]
Just 3 more days!  WooHoo!

**Comment by nileshprasad137** [comment]
@aethelwulffe I'll get back to this asap. Also, I'd like to work on the format of other reports during the summer , Posting Screen,etc.

**Comment by nileshprasad137** [comment]
> It would be good to have the facility information on the receipt. Get rid of the UAC Appl and UAC tot information. Add provider name. That ought to be good for now.

I think of wrapping this up by making these changes .

**Comment by aethelwulffe** [comment]
Note:  It is real important for the end users to be able to select what facility goes on a particular statement or receipt.  Obviously, the facilities marked as "billing facilities" (in the practice UI you are going to be re-writing soon anyway) should be the first choices, but the clinic may have a legal name, a couple of hundred (especially for assisted living facilities) different facilities, and several of those may have names that need to go on the output file instead of the actual legal entity...or vice versa.

**Comment by nileshprasad137** [comment]
After latest commit:
capture

Currently, user would be able to select facility if he visits `Reports->Financial->Pat Ledger ` but he is unable to select from the patient screen itself.

**Comment by tmccormi** [comment]
@teryhill is this ready to merge?

**Comment by teryhill** [comment]
Looks good to me asfar as the printout. I have not looked at the code.

**Comment by aethelwulffe** [comment]
Uh...Nilesh is doing this weird thing in the code where he sticks to one scripting language for like more than half of a line at a time...I thought in PHP you had to randomly write <?php every few characters... 😈 .  Yeah, the code looks good to me.

**Comment by tmccormi** [comment]
your funny....

**Comment by aethelwulffe** [comment]
Not as funny as you're.

**Comment by tmccormi** [comment]
Check it online ... fixed that typo, but dang github has not email notice dealy and not update notices...

**Comment by tmccormi** [comment]
And as you may have noticed my type+send is faster than my +edit phase.

**Comment by teryhill** [comment]
The only thing I noticed in my real quick testing is that provider is not the provider in the patient file but it is the provider selected in the report  and comes up all in the patient print.

**Comment by aethelwulffe** [comment]
Ouch.
It needs to be the billing/rendering provider from the billing table (as transposed to form_encounter after a fee sheet is saved) or the per-line-item provider from the billing table, and not the "provider_id" from demographics though...generally speaking...and should be able to do "authorized" status checks on those items if someone is smart enough to use those checkboxes in the fee sheet...assuming the feature is turned on.   However...we can't get everything in one commit...

**Comment by tmccormi** [comment]
should I revert?

**Comment by nileshprasad137** [comment]
Yes! I think you should revert it. I'd look at them today. I think ledger
had the same behaviour, so I did it that way. I'm not fully aware of many
billing concepts,that's what creating problems.

**Comment by tmccormi** [comment]
reverted.

**Comment by tmccormi** [comment]
Do a new pull request, please

**Pull request merged**
