### PR TITLE
Clean up JQuery Redundancy and version overlaps

### PR DESCRIPTION
**Pull request by tmccormi**
Goal:  get rid of legacy jquery.  Enable global variable to determine
what file to use so that upgrades are instantaneous.  Compress, remove,
or combine "custom" js components.

### CODE REVIEW

**Comment by tmccormi** [comment]
@aethelwulffe take a look at this branch and let me know if it looks good.

This is what I did
`git checkout -b JQuery_Redux origin/JQuery_Redux`
`git merge development_101`
`git checkout development_101` 
`git merge --no-ff JQuery_Redux`
`git log`
`git rebase -i b881f31`
 
REBASE / SQUASH Screen
`pick dcd4784 holistic replace and removal of old jquery ranges`
`fixup d936997 jquery updates`
`fixup 9b4904f jquery redux`
`fixup 1e0ab57 Upgrade jquery initial commit`
`fixup c38b2f9 holistic replace and removal of old jquery ranges`
`fixup 3ce534d jquery updates`
`fixup 150f772 jquery redux`

`Rebase b881f31..66a59c5 onto b881f31`
SAVE & EXECUTE

RESOLVE CONFLICTs
`diffuse custom/download_qrda.php`
`git add custom/download_qrda.php`
`diffuse interface/reports/patient_list_creation.php`
`git add interface/reports/patient_list_creation.php`
`git rebase --continue`
`git checkout -b JQuery_Redux_Squashed`

THEN cherry-picked your fix.
`git fetch origin`
`git cherry-pick 9cbefe56d0`
`git log`
`git rebase -i b923d27`

**Comment by aethelwulffe** [comment]
Will begin checking it out after din-din.

**Comment by aethelwulffe** [comment]
This branch only has 209 files changed vs 255.  That might have something to do with the merge "rebase" crap that does not seem to work.
I will see what comes up.

**Comment by aethelwulffe** [comment]
oK, there are no differences.  Killing the old branch

**Comment by aethelwulffe** [comment]
Any prognosis on getting this to dev?  I have a number of changes I am ready to drop into a new _sequential_ branch if this moves forward.

**Comment by tmccormi** [comment]
Did it test OK after I merged it all?

**Comment by aethelwulffe** [comment]
I found that it was completely identical to the original branch...but I will have one more go right now.  the create patient issue was a pain with the original branch, and I hope that the merge/squash stuff included that in the rebase.  This takes a long while to test....

**Comment by aethelwulffe** [comment]
Too many issues to deal with.
I don't know if there are just issues with what it is base off of or if all the issues are this branch...I just know I am getting notices that functions like indexOf are returning 304 and the PHP notice error says "i.indexOf is not a function" when I can look in the min.js it is calling and SEE it there.  Argh.

I am closing this request, and leaving the branch until no later than Jan1.  I will snuff it after that if there is no joy in getting _something out of this_.
image

**Pull request closed without merging**
