### PR TITLE
Fixing the hover of all themes for Finder

### PR DESCRIPTION
**Pull request by nileshprasad137**
Fixed the hover on selected items in Finder.

### CODE REVIEW

**Comment by teryhill** [comment]
Good Job on getting the commit in. I am GIT Impaired my self 8^)

**Comment by nileshprasad137** [comment]
I got a lot to learn about Git , different branches , ..etc. Initially , for my own institute projects ,I used to work only with master!!  :sweat_smile:

**Comment by teryhill** [comment]
I got some stuff on bitbucket and on Git and they both have their differences. Have not used Master

**Comment by aethelwulffe** [comment]
Let's give this one the thumb.  It is ready to go.  Stick a fork in it.  It has the urge to merge.

**Comment by aethelwulffe** [comment]
@teryhill  Could you look these over one last time, and do the thumb thing one way or another?

**Comment by teryhill** [comment]
Sorry had a thumbs up on 472

**Comment by aethelwulffe** [comment]
We went over this commit a good number of times.  We have at least two tests, and three pairs of eyes.  Merging.

**Pull request merged**
