### PR TITLE
These are the assets used in portal

### PR DESCRIPTION
**Pull request by teryhill**
The blink is for PFB we will look at removing jquery 1.5 1nd 1.11 #416

### CODE REVIEW

**Comment by teryhill** [comment]
just maybe the jquery 1.5 and 1.11 along with 1.19 and 2.0 as soon as things are refactored. If we are going to run on tablets we need some of the stuff.

**Comment by teryhill** [comment]
The current asset directory adds 15.2 meg to the overall project. Not a huge increase in my opinion

**Comment by teryhill** [comment]
The project is still 100 meg smaller than the O

**Comment by aethelwulffe** [comment]
Well, I am pretty sure that when this is done, a lot more will get snuffed than you just added.
There shouldn't be any issues with merging this (protests) as we all seemed to have a good idea of what is wanted, so I think we should keep moving and let this get to the test point.

**Pull request merged**
