### PR TITLE
#446 Issue Added file Installation on Windows with xampp 

### PR DESCRIPTION
**Pull request by rksahu17**
@teryhill @tmccormi If it has to be in html format please comment I would convert it to html. Give suggestion for  further changes if any.

### CODE REVIEW

**Comment by rksahu17** [comment]
@aethelwulffe please see the changes

**Comment by nileshprasad137** [comment]
Bro, don't use several commits on a single pull request. Even I did that mistake earlier , so i wanted to just advise you.

**Comment by rksahu17** [comment]
Okay, I will keep in mind that. But is there any problem with that..

**Comment by rksahu17** [comment]
@teryhill @aethelwulffe @tmccormi review this pull request...

**Comment by rksahu17** [comment]
@robbyoconnor review this pull

**Comment by aethelwulffe** [comment]
@rksahu17 
Uh, Rajesh...the files you deleted are actually required (in the given format for the most part) by the windows installer script, it took me a long time to get them into the code base...and I just recently finally got them in. 😉   The installer .exe package comes with a copy of xampp lite that already has the apache, php, and mariaDB parameters set.  In that context, the additional configuration instructions are not needed.  I was suggesting that you _look_ at it for general reference (and yes, discuss any weaknesses you saw in that context) and use anything you like out of that package to make (what I thought you were looking to do) a single document for those folks installing with a "roll your own" xampp installation (as they may also want filezilla, tomcat, mercury, or something else).

**Comment by robbyoconnor** [comment]
I'm gonna close this. If you're gonna do Google Summer of Code, learn git.

**Comment by robbyoconnor** [comment]
You should know how to rebase.

**Comment by robbyoconnor** [comment]
I'd recommend opening a new PR

**Pull request closed without merging**
