### PR TITLE
Flowboard layout fix

### PR DESCRIPTION
**Pull request by MigDinny**
Before:
image

After:
image

The checkbox was repositioned to the settings option list. There is a hidden input there that probably should not be removed, I guess.

#783

### CODE REVIEW

**Comment by teryhill** [comment]
You need to fix the function topatient(newpid, enc) . form_new_window no longer exists. This prevents the opening on the patient demographics in a separate window

**Comment by Trodrige** [comment]
Good to me

**Comment by Trodrige** [comment]
> Good to me

Scratch that!!! 
Hi, @MigDinny you did well here. Just some little instructions you have to follow here. The task description says you should
> select an existing issue from the Issue Tracker on GitHub, and fix it. Please reference it in your pull request description like Fixes #123, where #123 is the issue number.

Just that and your work is complete.

**Comment by MigDinny** [comment]
@Trodrige it is at the end of the first post. Isn't it enough? Do i have to do it on the title?

**Comment by MigDinny** [comment]
#783 
It's on the end of the description

**Comment by Trodrige** [comment]
Ooops, sorry. It's on me! It'll be good if the issue number comes first. Before "Before:" 
I think "Fixes #787" is real good.

**Comment by aethelwulffe** [comment]
OK, Looks like the issue linking discussion is resolved.  Merging after syntax check.  Actual test data not easy for me at this point, so if @teryhill and @Trodrige you have not had full tests, say something now.

**Comment by teryhill** [comment]
Pull the trigger @aethelwulffe

**Comment by teryhill** [comment]
@aethelwulffe  are you squashing and merging?

**Comment by aethelwulffe** [comment]
@teryhill if you can squash and merge, then do so.

**Comment by aethelwulffe** [comment]
I got lost at the pttrk_ function thingie...LOST!

**Comment by teryhill** [comment]
Merged

**Pull request merged**
