### PR TITLE
Small fix to the patient finder criteria.

### PR DESCRIPTION
**Pull request by teryhill**
Small fix to the patient finder criteria.

### CODE REVIEW

**Comment by tmccormi** [comment]
Yes drop SSN from the search

**Comment by aethelwulffe** [comment]
Yeah...heh...If you want some sort of public ID...Hey, I know what field 
you could use!! :-P

**Comment by aethelwulffe** [comment]
And someone merge 713 before I have a conniption.

**Comment by teryhill** [comment]
SSn removed

**Pull request merged**
