### PR TITLE
fix to patient finder default filter for zero row

### PR DESCRIPTION
**Pull request by kchapple**

### CODE REVIEW

**Comment by tmccormi** [comment]
I'll cherry pick this over to master as well, for future.

**Comment by aethelwulffe** [comment]
Good.
I marked this as "User Request" as a sort of priority marker.  I figure if someone; a clinic or a specific vendor or the like really requires a change, it should deserve special consideration (in a number of aspects).

**Comment by teryhill** [comment]
What did it do?

**Comment by aethelwulffe** [comment]
I didn't have time to review it or look at it before it got merged...:-\

**Comment by tmccormi** [comment]
It a minor tweak that lets a custom module that calls the finder with a preloaded search selection work without the user having to "submit" the search before runs the filter.  Has no effect on base functionality.

**Pull request merged**
