### PR TITLE
Admin Menu Edit UI and minor tweaks to menu support

### PR DESCRIPTION
**Pull request by tmccormi**
Full JSON tree editor, drag and drop, search, block delete, etc.

### CODE REVIEW

**Comment by teryhill** [comment]
I don't know seems like a lot of baggage for just one feature 8^)

**Comment by aethelwulffe** [comment]
Vector graphics and stuff hunh?

**Comment by tmccormi** [comment]
one of the cool things that comes with the baggage is having all the icons in a vector file.   Need to figure out how that works.

**Comment by aethelwulffe** [comment]
Just ask Bezier...he knows.

**Comment by teryhill** [comment]
Who's Bezier?

**Comment by tmccormi** [comment]
I could drop all the docs/* and the map file which is just for debugging

**Comment by teryhill** [comment]
Put them on a list "To Drop" I think they are necessary until we learn this

**Comment by tmccormi** [comment]
Good enough.  OK to merge then?  anyone else played with it yet?

**Comment by teryhill** [comment]
Haven't plated with it. Do you think it needs to stay in the tabs directory or be put in the main core?

**Comment by tmccormi** [comment]
It's just for the menu, so where it is now is fine.  If we start using JSON in a lot of places (like maybe a new globals configuration or document categories) we can promote it.

**Comment by teryhill** [comment]
so make a mental note that it is used like bootstrap in tabs

**Comment by tmccormi** [comment]
bootstrap is apparently in the zend_modules too ..  some of it, anyway

**Comment by teryhill** [comment]
Yep I think that bootstrap needs to be moved to where ever we are going to be putting the assets

**Comment by tmccormi** [comment]
so ... merge now?

**Comment by teryhill** [comment]
I am ok with merging it  need a vote from @aethelwulffe  Ohhh Art

**Comment by aethelwulffe** [comment]
Art was out glamping this weekend.  Bezier is famous for curves and points...something in that geometria stuff...thus is a reference to SVG images....and I gave this a thumbs-up three days ago.

**Pull request merged**
