### PR TITLE
Add title to Patient/Client -> Visit Forms -> Review of Systems

### PR DESCRIPTION
**Pull request by Jdew192837**
Partly #888
(Missing tab titles for a clinical form)

### CODE REVIEW

**Comment by Jdew192837** [comment]
Before:
=====
screenshot 11

After:
====
screenshot 12

**Comment by Jdew192837** [comment]
PTAL @teryhill @aethelwulffe ! :)

**Comment by aethelwulffe** [comment]
This file is "review of systems" clinical form, not "Miscellaneous Billing Options"

**Comment by Jdew192837** [comment]
Sorry about that @aethelwulffe

**Comment by teryhill** [comment]
@tmccormi Can you review this?

**Comment by aethelwulffe** [comment]
Three days with two approvals and no downvotes.
Merging.  Good job @Jdew192837

**Pull request merged**
