### PR TITLE
Add title to Patient/Client -> Visit Forms -> Misc Billing Options

### PR DESCRIPTION
**Pull request by Jdew192837**
Partly #888

### CODE REVIEW

**Comment by Jdew192837** [comment]
Before:
=====
screenshot 9

After:
====
screenshot 10

**Comment by Jdew192837** [comment]
PTAL @teryhill & @aethelwulffe ! :)

**Comment by Jdew192837** [comment]
@Trodrige @teryhill @tmccormi @aethelwulffe 
PTAL,
Think it's all ready PTAL at #938 
Thanks,
jdew192837 (nulxis)

**Comment by aethelwulffe** [comment]
Three  days with two approvals and no down-votes.  Merging.

**Pull request merged**
