### PR TITLE
initial commit for assets 

### PR DESCRIPTION
**Pull request by teryhill**
initial commit. making sure I am following the correct guidelines. Where do we want things like Knockout, bootstrap, backbone,etc. I understand the jquery's go under js but not sure about the others #372

### CODE REVIEW

**Comment by aethelwulffe** [comment]
Should we change /js to /dependencies or /lib?  I have the funny feeling 
that most of the dependencies are in fact going to be javascript, but do 
they really need to be separated by type if they are something else?  I 
think /js is a pretty familiar concept.  Since Knockout, Bootstrap, 
Backbone, Gritter, Jquery, Ajax and all that are all javascript, it 
seems to take care of everything.  (?)

**Comment by teryhill** [comment]
I don't have an issue with putting them under js .

**Comment by aethelwulffe** [comment]
I suppose there was already talk about using the global variables to 
determine what version of a dependency should be used etc... so maybe 
including the old packages is part of the plan.  Please remind me of 
what was discussed on the phone call.

**Comment by aethelwulffe** [comment]
My understanding of JQUERY:

Version 1.x supports ancient I.E.

Version 2.x has the same API as 1.x, while dropping the old IE 
compatibility.

Version 3.x works a little differently.

JQuery-Compat 3.x takes over the job of the 1.x for compatibility of 
IE8, Opera12, and Safari5 and other junk.

JQuery 3.x does not have the compatibility bits.

Both 3.x varieties use the same public API, and otherwise match features 
by version.

https://github.com/jquery/jquery-migrate/  is a tool we can use to 
identify and migrate jquery versions.

In my opinion, we should be able to test everything with this, upgrade 
code where needed and all that.

**Comment by teryhill** [comment]
I think we should, since we are beginning this , put the latest versions in the asets dir and migrate

**Comment by aethelwulffe** [comment]
I will post the above to a jquery upgrade issue.
Please look up the difference between the slim and regular versions of the standard and compatibility versions (4 flavors) and pull down the .min versions of each for this commit.
I will get pieces into play to get the upgrade moving in a more professional manner than the trial and error method.

**Comment by teryhill** [comment]
sounds like a plan

**Pull request merged**
