### PR TITLE
deprecate left_nav

### PR DESCRIPTION
**Pull request by aethelwulffe**
leave left_nav to leverage more levity.
left_nav and daemon_frame gone.
#374

### CODE REVIEW

**Comment by tmccormi** [comment]
if only you dropped the concurrent_layout and leftnav width and other crap that goes with it, I'd be in hog heaven

**Comment by aethelwulffe** [comment]
I'll get along with it.  I think concurrent layout is a bit of a job, 
and some scary stuff happened when I went chop-chop.

**Comment by aethelwulffe** [comment]
I tried, and something went funny.  Thought about making a comment that 
it needed doing...so maybe I can try again...or you can push one?

**Comment by tmccormi** [comment]
wouldn't be the first time we tried that an reverted ...

**Pull request merged**
