### PR TITLE
Encounter by carrier

### PR DESCRIPTION
**Pull request by teryhill**
#555 Not sure why I have Arts commit for Dan in this.

### CODE REVIEW

**Comment by teryhill** [comment]
If we decided on the theme to use we could cut out all the rest of them. It has the options to use arrows to indicate direction but I had issues figuring that out and could not get it to show properly , If some one else can figure it out that would be great. I needed it to be done , you know that under the gun stuff.

**Comment by aethelwulffe** [comment]
Yeah, I am pretty familiar with having an artillery piece laying on top 
of me while people are pinging me with a bb-gun.

If you see a default theme you think would be a good look...otherwise 
maybe I will see if there is a way to integrate the themes with the 
application's flavor of them.

**Comment by teryhill** [comment]
@aethelwulffe see if that's more gooder.

**Comment by tmccormi** [comment]
Is this one ready to merge?

**Comment by teryhill** [comment]
Unless you guys want to change the name or something Yes it is ready

**Pull request merged**
