### PR TITLE
Add frame resizing capability

### PR DESCRIPTION
**Pull request by azwreith**
Hey guys! Check out this trial version. I was initially having problems due to mouse movements being blocked by iframes but I solved it using a transparent layer whenever we are resizing

It goes a little bit crazy when 3 frames are open so I'll have to modify the formula a bit for that.

I didn't use JQueryUI because importing that whole thing for such small use seems like a waste of resources.

Thanks!

### CODE REVIEW

**Comment by azwreith** [comment]
Addresses #457

**Comment by teryhill** [comment]
There are versions of UI on the system. What version do you want to use? This is what I get for the inital screen using chrome

image

When I try to resize it I get this with one click and it will not return to the previous screen size.

image

**Comment by azwreith** [comment]
Well, on the main page we are using JQuery 2.2.0. A compatible JQueryUI would be 1.12.1 I guess. The latest one we have, 1.8.21, was giving errors with the JQuery version.
Anyway, I think this is a better approach, though the code is bigger.

Hm..that's strange, can you check whever you get the `handle` div in the center? It should look something like this:
image

**Comment by teryhill** [comment]
@azwreith  Does this help?

image

**Comment by azwreith** [comment]
Yes it does! Ahh, it seems like you still have the old tabs.css file

**Comment by teryhill** [comment]
The original tabs.css is on the left the change is on the right

image

**Comment by azwreith** [comment]
Oh I got it! Chrome is loading the css from the cache so you gotta open dev tools (Ctrl+Shift+i) and then right click the refresh button (next to search bar) and click "Empty Cache and Hard Reload"

**Comment by teryhill** [comment]
sometimes I hate cache. That was it sorry I usually do a refresh just been putting in some extra hours trying to stay up with you young guns.

**Comment by teryhill** [comment]
I like that change. Can you set it up on a global to turn it off or on?

**Comment by azwreith** [comment]
Yes yes, cache has destroyed all our lives xD
Well, you deserve a nice relaxing weekend.

So how's it looking?

On Mar 5, 2017 4:41 AM, "Terry Hill" <notifications@github.com> wrote:

sometimes I hate cache. That was it sorry I usually do a refresh just been
putting in some extra hours trying to stay up with you young guns.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LibreHealthIO/LibreEHR/pull/470#issuecomment-284191720>,
or mute the thread

**Comment by teryhill** [comment]
Look at #420 I think you can handle that one also 8^)

**Comment by teryhill** [comment]
Thanks but I still have code to do for my customers so the weekend is still very busy. I do take Sunday off.

**Comment by teryhill** [comment]
can you look at opening 3 and 4 frames. I don't think the screens size is good with more than 4 open, What do you think?

**Comment by teryhill** [comment]
@azwreith  here's another thing, if the all tabs are unlocked the active tab only take's up the original size, can you make it go full frame when only one frame is active? Try it with 3 frames unlocked and you will see what I am talking about.

image

**Comment by aethelwulffe** [comment]
Hint:  Browser options: "delete all history when closing firefox."

**Comment by aethelwulffe** [comment]
Terry, give this a review or approval please.  This should be merged before some of the other pieces, and I don't want to see it stomped on.

**Comment by aethelwulffe** [comment]
This still has the issue of needing to "spring" back to take up the unused space...Is that a usability issue?

**Comment by azwreith** [comment]
Hey guys! I was out all day yesterday. The jumping with 3 tabs and the tab not taking up the either frame issues are caused because of the formula, which needs to be modified. I'll push a commit with the changes today :3

**Comment by aethelwulffe** [comment]
Glad to hear it Ujjwal.  This is a LONG awaited improvement.  It is probably the most important piece of the tabs system that was missing.

**Comment by aethelwulffe** [comment]
Oh heck yeah.  I am testing NOW!

**Comment by azwreith** [comment]
I updated the formula to accommodate tabs springing back when alone. It's still a bit jittery but works :smile:

**Comment by aethelwulffe** [comment]
It does have a bit of a jitter, but not real bad.  That behaviour is complex though, and unless we slow down the change with some sort of smooth transition, It will likely be that way.  It looks good to me, and I am hitting my thumbs up.

**Comment by teryhill** [comment]
Looks good in testing. Thanks @azwreith

**Comment by aethelwulffe** [comment]
@teryhill if you have given this a final test, I would like to merge it.

**Comment by aethelwulffe** [comment]
Oh, I see you did.  OK, I will merge.

**Comment by teryhill** [comment]
@aethelwulffe Merge it and we will give it a shake down over the course of development. Also merge @nileshprasad137  stuff and get it in

**Pull request merged**
