### PR TITLE
Fix for delete patient.

### PR DESCRIPTION
**Pull request by pri2si17-1997**
Signed-off-by: Priyanshu Sinha <pksinha217@gmail.com>

### CODE REVIEW

**Comment by pri2si17-1997** [comment]
Hello @teryhill @aethelwulffe .

This references #531 .

Please do have a look at it and let me know if anything I'm missing.

**Comment by teryhill** [comment]
works good for me. Did you look at Kevin's suggestion ?

**Comment by aethelwulffe** [comment]
Good work Priyanshu!

**Comment by pri2si17-1997** [comment]
Thanks @aethelwulffe @teryhill :)

Yes @teryhill . I looked at Kevin's suggestion. `if (opener && opener.imdeleted) opener.imdeleted(); else parent.imdeleted()`, this line was giving `Uncaught type error` exception, as it was not able to call `clearPatient()`. For the time being I commented out that line. There can be modification to incorporate this as well as your suggestion of hard delete and soft delete. I will look into that, but right now I'm busy with my academic projects. Once done, I'll let you know.

Right now this PR only addresses the reload of page as soon as patient is deleted.

**Comment by teryhill** [comment]
Take care of the School work that is the most important.

**Pull request merged**
