### PR TITLE
Add option of FlowBoard login only in full screen

### PR DESCRIPTION
**Pull request by prabhakarpd7284**
Solve #971 

- Add FlowBoard Login check in login page.
login

- When box is checked, only FlowBoard opens in full screen.

flb

### CODE REVIEW

**Comment by aethelwulffe** [comment]
@prabhakarpd7284 
1.  We should toggle this option with a global (enable_flowboard_only or something).
2.  This might be something that could/should be toggled within user prefs or within the user config.

**Comment by prabhakarpd7284** [comment]
@aethelwulffe 
This seems like a fine approach.
I will work on your suggestions.

**Comment by aethelwulffe** [comment]
Thank you @prabhakarpd7284 .  You have a functional piece here.  This little bit of polish turns it into a significant feature.  The push to enable a "kiosk" or special terminal access port is really helped by this.  I encourage you to look at this as an opportunity to put hooks in so that any number of single-function-only settings could be selected.  If we have the methods formalized, we can start getting away from GACL, and replacing it with something coherent and native.

**Comment by teryhill** [comment]
replaced by pr 1043 Duplicate

**Pull request closed without merging**
