### PR TITLE
Replacing Smarty Engine with native php

### PR DESCRIPTION
**Pull request by nileshprasad137**
**Summary of changes::**
Made Controller class smarty independent so that complete Administration/Practice section becomes Smarty independent.
Replaced Smarty templates with native PHP templates. Note, UI has been retained same for now. I'll be making changes in UI down the road, in some other pull request.

@aethelwulffe @tmccormi Give it a test. I haven't copied these to new folder so you need not change path in Menu.

### CODE REVIEW

**Comment by tmccormi** [comment]
I'll test this branch today and provide feedback as appropriate.  Has anyone else played with it yet?

**Comment by teryhill** [comment]
The last one I tested was thru the document class changes.

**Comment by nileshprasad137** [comment]
Yea, give "documents" a close look. Rest all should be fine I guess.

**Comment by aethelwulffe** [comment]
I didn't try everything on the clinical forms, but everything else looks like it is working

**Comment by tmccormi** [comment]
I will take one more pass and likely merge this tonight.

**Comment by aethelwulffe** [comment]
WoooHoo!

**Comment by nileshprasad137** [comment]
That'll be great. I'll remove rest of the Smarty after I am done with UI. Had been busy for past few days learning mobile app dev.

**Pull request merged**
