### PR TITLE
Flowboard input alignment

### PR DESCRIPTION
**Pull request by MigDinny**
Fixes issue: #794 

Before:
image

After:
image

### CODE REVIEW

**Comment by Trodrige** [comment]
@MigDinny it is better to specify the issue a pull request is meant for at the top. 
That is " Fixes #794 " should come before the screenshots.

**Comment by MigDinny** [comment]
@Trodrige check it out now

**Comment by MigDinny** [comment]
@Trodrige I commited a new change because I realized now the work wasn't complete. But here it is.

**Comment by aethelwulffe** [comment]
Good code, good reviews.  Thanks folks, merging...

**Pull request merged**
