### PR TITLE
First run at the date picker change

### PR DESCRIPTION
**Pull request by teryhill**
First run at the date picker change These have been tested to ensure
that the date picker code functions #15

### CODE REVIEW

**Comment by teryhill** [comment]
Will be working thru some more in the AM

**Comment by teryhill** [comment]
The forms directory was not tested.

**Comment by tmccormi** [comment]
Shall we keep this open or merge as you go?

**Comment by teryhill** [comment]
It does not matter to me. I would like some one to test the forms. I don't have very many left on your list. I also fixed some other issues with the code , inventory menu items missing, pieces not working here or in the other place etc.

**Comment by teryhill** [comment]
The only 2 files I have not done aside from the ones that are deleted or are in the new portal are /interface/new/new.php and newcomprehensive.php. These need to be done with the demographics files.

**Comment by teryhill** [comment]
I am finished with this for now. I will start gathering up the strays in another PR

**Comment by tmccormi** [comment]
You rock.

**Pull request merged**
