### PR TITLE
Fix for screen not saving

### PR DESCRIPTION
**Pull request by teryhill**
Fix for screen not saving #460 I had the wrong version of jquery being loaded, I had 1.9.1 and it should be 1.7.2

### CODE REVIEW

**Comment by teryhill** [comment]
@aethelwulffe  @tmccormi Look at this please

**Comment by aethelwulffe** [comment]
What function is it that causes it to have an issue with the (slightly) newer version?  We do have a deprecation list available.

**Comment by teryhill** [comment]
Don't know figured that was on the jquery list 8^)

**Comment by aethelwulffe** [comment]
OK...make it work, then we will deal with the JQUERY list. :)

**Comment by aethelwulffe** [comment]
Review issue deferred to the jquery cleanup project that will likely be a GSOC project.  This is a one-line fix for something that is totally broken at the moment.

**Pull request merged**
