### PR TITLE
fix color picker bug

### PR DESCRIPTION
**Pull request by naveen17797**
screenshot from 2018-03-13 12-30-13
color picker bug fixed
Both backgrounds have set white as default bg color
some improvements made on nav bar as well as buttons

### CODE REVIEW

**Comment by naveen17797** [comment]
@aethelwulffe  @teryhill review this, i am working on that contrast comparison thing.it is still not added.

**Comment by naveen17797** [comment]
issues on this bug
#1056 
#1059

**Comment by teryhill** [comment]
I have tested this and it improves the color picker great job @naveen17797 .

**Comment by naveen17797** [comment]
Thanks @teryhill

**Comment by aethelwulffe** [comment]
What about the comments I left?
Does style_purple require the changes?
Need a normalized file ending on style.php

**Comment by teryhill** [comment]
@aethelwulffe isn't php an normalized file ending?

**Comment by aethelwulffe** [comment]
Git can screw up diffs if all the files in a repo don't have the same line ending.  The standard is crlf here, and elsewhere on github.
That is why we sometimes (in the past most of all) used to see strange issues.
Search "github normalize file endings" for more...lots more.  Probably ought to do a huge PR to fix everything in one go.

**Comment by teryhill** [comment]
Duh ok so it needs a blank line at the end of the file.

**Comment by aethelwulffe** [comment]
That's what the nerds tell me.

**Pull request merged**
