### PR TITLE
DatePicker in add patients section can add future dates.

### PR DESCRIPTION
**Pull request by naveen17797**
before fix
screenshot from 2018-02-16 09-12-05
after fix
screenshot from 2018-02-16 11-57-32

**# Even if the user adds future date, it will be converted to current date.**

### CODE REVIEW

**Comment by teryhill** [comment]
yes server side

**Comment by aethelwulffe** [comment]
$(document).ready(function(){
    $('#myDate').attr('min', todayDate());
});

**Comment by teryhill** [comment]
@aethelwulffe does that stop you from manually entering a date in the future. The current set up of the date picker will stop the future date but not if it is entered manually.

**Comment by naveen17797** [comment]
yes it is not validated in server side.

**Comment by aethelwulffe** [comment]
Well, our test patients "Martha Washington" and George Washington will be be harder to replicate with a 150 year age limit, but this looks good.  Getting it into my test line-up now.

**Comment by naveen17797** [comment]
See also pull #1012 its more important than this one.

**Comment by teryhill** [comment]
@aethelwulffe this is a duplicate pr @naveen17797 will be deleting it

**Comment by aethelwulffe** [comment]
I think I realized that just a little while ago...

**Pull request closed without merging**
