### PR TITLE
Fixed download pdf report for patient.

### PR DESCRIPTION
**Pull request by pri2si17-1997**
Signed-off-by: Priyanshu Sinha <pksinha217@gmail.com>

### CODE REVIEW

**Comment by pri2si17-1997** [comment]
Hello @aethelwulffe @teryhill . This addresses #536.

Please have a look at it and let me know if anything missing. This removes old files and is working on my system with Ubuntu 16.04 and PHP 7.0.

**Comment by nileshprasad137** [comment]
@pri2si17-1997 you made changes only in  `interface/patient_file/report/custom_report.php` , right?

**Comment by pri2si17-1997** [comment]
No @nileshprasad137 I have upgraded html2pdf also.

**Comment by nileshprasad137** [comment]
Okay !! You upgraded that module. I didn't see that.

**Comment by aethelwulffe** [comment]
He added a new directory with what I think is the latest version.  That is great. I am not seeing removal of the old version as yet.
I would suggest that you review the relative sizes of the packages, pare down the excess (there is a lot), add the copyright/attribution notices to the main attribution page, and stick in the libreehr module notes etc...  I think most of the documents like "News" and the like can be safely pared down, and simply providing a link to their project for up-to-date information about the module source would be sufficient.  Currently we are adding hundreds of excess files that we will never call, and the user will never see, but we will be shlepping back and forth (and grepping) constantly.

**Comment by aethelwulffe** [comment]
LibreEHR/modules/html2pdf/html2pdf_mod_docs/html2pdf4LEHR_readme.md etc...

**Comment by aethelwulffe** [comment]
Previous upgrade notes in README_libreehr.txt:
This html2pdf library was updated by:

1. Removing all old files

2. Downloading HTML2PDF 4.5.0 from:
   https://github.com/spipu/html2pdf/releases (composer package)

3. Running composer command "composer install"

4. Requiring "setasign/fpdi": "1.6.*" for latest FPDI package

5. Removing the examples directory from the html2pdf directory.

6. Modifying library/html2pdf/_class/myPdf.class.php so that HTML2PDF_myPdf extends FPDI instead of TCPDF.
   Note that FPDI extends TCPDF.

7. Modifying interface/patient_file/report/custom_report.php line # 52 to require html2pdf/vendor/autoload.php rather html2pdf.class.php

8. Passing two new parameters "unicode and encoding" to HTML2PDF constructor in interface/patient_file/report/custom_report.php on line 57 and 58 respectively

9. Modifying library/html2pdf/vendor/setasign/fpdi/fpdi_bridge.php class removing second parameter "false" of "class_exists" method because TCPDF is autoloading

10. Removed examples directory from the TCPDF package.

At this point the HTML2PDF(version 4.5.0) with TCPDF(version 6.2.12) and FPDI(version 1.6.1) is installed and working.

**Comment by pri2si17-1997** [comment]
Yes @aethelwulffe.

Ya old version should be removed. I will do that.

**Comment by aethelwulffe** [comment]
I would suggest leaving the version out of the name (just html2pdf).  This is a "core" module, and upgrades to it should not require base-code paths to change with version numbers.

**Comment by aethelwulffe** [comment]
189 out of 265 files in this package will never be called, and I am not totally sure of all of the other 76.

**Comment by aethelwulffe** [comment]
@pri2si17-1997  The OpenEMR guideline would have been totally good, but we sort of added some extra organizational bits to treat it as a module.
The shock to me is that somehow the "Making a module" readme never made it into the docs...and I think we need to have a discussion again (against a pull request to the docs directory) about what a module is and how to deploy it.  Hopefully I can track down that original .md I made for this purpose.

**Comment by pri2si17-1997** [comment]
Ok @aethelwulffe . Will surely remove those files. I will have to look at that.

For the time being we can install it locally on our systems, till we have all things fixed.

**Comment by aethelwulffe** [comment]
@pri2si17-1997 If you would like me to branch off of your branch and play at tweaking, I have time today.  We need your input (As well as from everyone else) on how best to use the "up-gradable  component as a module" concept.

**Comment by pri2si17-1997** [comment]
Ya sure @aethelwulffe .

**Comment by aethelwulffe** [comment]
I got a "failed to clone" error off of your repo.  I will try again in a bit.

**Comment by aethelwulffe** [comment]
Reference #541 @pri2si17-1997

**Comment by tmccormi** [comment]
OK, I'm lost now.   I'll merge stuff when someone approves this and or the other #539 related.  These are not easy to sort out what the status is..

**Comment by aethelwulffe** [comment]
We are working it out and will let you know when it is a GO.

**Comment by aethelwulffe** [comment]
#542 is the PR for this issue. #536 is the issue.  After 542 is merged, all three may be closed.

**Pull request closed without merging**
