### PR TITLE
Fixed the height and width of input box in interface/login/login.php

### PR DESCRIPTION
**Pull request by pri2si17-1997**
Signed-off-by: Priyanshu Sinha <pksinha217@gmail.com>

### CODE REVIEW

**Comment by teryhill** [comment]
@tmccormi I don't see an issue with this but you are the goto guy on looks 8^)

**Comment by teryhill** [comment]
Looks good @pri2si17-1997

**Comment by pri2si17-1997** [comment]
@teryhill 
is this ok? Or any loop hole?

**Comment by pri2si17-1997** [comment]
@aethelwulffe 
No, i haven't got any screenshot.

**Comment by teryhill** [comment]
@aethelwulffe  I have tested this and it works here is a before and after.
Before
invisible_fonts

After

newvisible

**Comment by aethelwulffe** [comment]
Much much better!

**Comment by aethelwulffe** [comment]
This is a simple change, and a clean implementation and branch.  It affects nothing else, and is a real improvement.  We have had three sets of eyes on it, and three independent tests.

**Pull request merged**
