### PR TITLE
Changes report preparing generator

### PR DESCRIPTION
**Pull request by Trodrige**
Pulling useful functions from reports, preparing the repository for building a report generator for EHR.

### CODE REVIEW

**Comment by aethelwulffe** [comment]
@Trodrige You seem to have included the TCM forms in this PR.

**Comment by Trodrige** [comment]
ooopsss @aethelwulffe thanks for noticing. Uhmm, they'll certainly be lots of updates and addition to this PR. Maybe @teryhill will be noticing other common functions that can be pulled out. 
@aethelwulffe please tell me if you notice any issues with this PR

**Comment by Trodrige** [comment]
I'm closing this PR. I've pushed the changes to [this new branch](https://github.com/LibreHealthIO/LibreEHR/tree/Changes_report_preparing_generator)

**Comment by aethelwulffe** [comment]
@Trodrige The pre-billing_issues report now has a menu item in the main branch.

**Pull request closed without merging**
