### PR TITLE
Added a Cancel button that was missing!

### PR DESCRIPTION
**Pull request by MigDinny**
Fixes: #861 

A cancel button was added that was missing.

### CODE REVIEW

**Comment by MigDinny** [comment]
image

Now there is a cancel button.

**Comment by teryhill** [comment]
This is how it should look.

image

**Comment by MigDinny** [comment]
Don't know if this can go or should be closed.

**Comment by aethelwulffe** [comment]
This should be fixed with Terry's revert of the patient search feature.  Once that is merged, we will be good.

**Comment by MigDinny** [comment]
I'll close this, then

**Pull request closed without merging**
